### ISSUE TITLE
ExternalSecrets should be have namespace prefix

### ISSUE THREAD

**Issue by peter-poki** [jenkins-x-plugins/jx-secret#342]
When creating external secrets it would be nice if newly created secrets in vault service (GKE,Azure, Aws,...) would have namespace prefix in their name.

E.g. If you have 2 environments in one cluster (staging and beta), then you define secret, it should be mapped to different vault secrets so that you can rotate/change them independently and they are different across environmets .

Currently you have to do this by creating externalSecret resource manually and create links to two different vault secrets.

Inspiration is in this thread:
https://kubernetes.slack.com/archives/C9MBGQJRH/p1625211231317400

**Comment by jstrachan** [comment]
this is a more flexible solution #351

though we do have support for an annotation you can use to conditionally use a different prefix in vault based on the environment/namespace: https://jenkins-x.io/v3/develop/faq/config/secrets/#how-do-i-configure-secrets-differently-in-staging-versus-production
